### REGISTER
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "test",
  "lastname": "test",
  "email": "test@mail.ru",
  "password": "111111"
}


### AUTHENTICATE
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "test@mail.ru",
  "password": "111111"
}

### ----- AUTH TOKEN -----

@authToken = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG1haWwucnUiLCJpYXQiOjE3NDcxNDY3MzQsImV4cCI6MTc0NzE0ODE3NH0.molZdpaldREBEzSGyVtTVsD0Bqe0CZGCqfTW9lmA6T4

### GET ALL SCOREBOARDS


GET http://localhost:8080/api/v1/scoreboard
Authorization: {{authToken}}


### GET SCOREBOARD BY ID
GET http://localhost:8080/api/v1/scoreboard/2
Authorization: {{authToken}}


### ADD SCOREBOARD
POST http://localhost:8080/api/v1/scoreboard
Content-Type: application/json
Authorization: {{authToken}}

{
  "score": 22212,
  "userId": 2
}


### UPDATE SCOREBOARD
PUT http://localhost:8080/api/v1/scoreboard
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": 2,
  "userId": 3,
  "score": 99999
}


### DELETE SCOREBOARD BY ID
DELETE http://localhost:8080/api/v1/scoreboard/4
Authorization: {{authToken}}


### GET KNOWLEDGEBASES
GET http://localhost:8080/api/v1/knowledgebase
Authorization: {{authToken}}


### GET KNOWLEDGEBASE BY ID
GET http://localhost:8080/api/v1/knowledgebase/1
Authorization: {{authToken}}


### ADD KNOWLEDGEBASE
POST http://localhost:8080/api/v1/knowledgebase
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "testKnowledgeBase",
  "content": "some html content"
}


### UPDATE KNOWLEDGEBASE
PUT http://localhost:8080/api/v1/knowledgebase
Content-Type: application/json
Authorization: {{authToken}}

{
  "id": 1,
  "name": "testKnowledgeBase Updated",
  "content": "some html content Updated"
}


### DELETE KNOWLEDGEBASE BY ID
DELETE http://localhost:8080/api/v1/knowledgebase/1
Content-Type: application/json
Authorization: {{authToken}}


### GET ALL SURVEYS
GET http://localhost:8080/api/v1/survey
Authorization: {{authToken}}


### GET SURVEY BY ID
GET http://localhost:8080/api/v1/survey/2
Authorization: {{authToken}}


### ADD SURVEY
POST http://localhost:8080/api/v1/survey
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "top Survey",
  "content": "top survey content"
}


### UPDATE SURVEY
PUT http://localhost:8080/api/v1/survey
Content-Type: application/json
Authorization: {{authToken}}

{
  "id" : 5,
  "name": "top Survey updated",
  "content": "top survey content updated"
}


### DELETE SURVEY
DELETE http://localhost:8080/api/v1/survey/5
Content-Type: application/json
Authorization: {{authToken}}


### GET ALL USERS FOR SURVEY BY ID
GET http://localhost:8080/api/v1/surveys/2/users
Authorization: {{authToken}}


### ADD USER TO SURVEY
POST http://localhost:8080/api/v1/surveys/2/users/1
Authorization: {{authToken}}


### DELETE USER FROM SURVEY
DELETE http://localhost:8080/api/v1/surveys/2/users/1
Authorization: {{authToken}}